### ISSUE TITLE
question: how to get started with CLDiff

### ISSUE THREAD

**Issue by monperrus** [FudanSELab/CLDIFF#1]
Hi all,

I'd like to use CLDiff, is there a tutorial on a small example?

Thanks,

--Martin

**Comment by Symbolk** [comment]
Though the test code can be helpful, complete documentations and comments in English are in urgent demand. Besides, the project structure can be improved. @calvinhkf 
A small example:
https://github.com/FudanSELab/CLDIFF/blob/master/src/edu/fdu/se/cldiff/CLDiffTest.java

**Comment by kaifeng-h** [comment]
You can run it in package _main.CmdTest.java_ when you set your own repo path, commit id and output directory in method _run_.  As @Symbolk noted, the project structure needs improving and also the output in the console is too verbose. I'm working on that. 
> Hi all,
> 
> I'd like to use CLDiff, is there a tutorial on a small example?
> 
> Thanks,
> 
> --Martin

**Comment by kaifeng-h** [comment]
Yes, the project structure is not good. It was written in a hurry and a lot of work needs to be done. Sorry for that.
> Though the test code can be helpful, complete documentations and comments in English are in urgent demand. Besides, the project structure can be improved. @calvinhkf
> A small example:
> https://github.com/FudanSELab/CLDIFF/blob/master/src/edu/fdu/se/cldiff/CLDiffTest.java

**Comment by monperrus** [comment]
> I'm working on that.
Thanks, looking forward to it

**Comment by Symbolk** [comment]
BTW, I am wondering how to start the web gui because it interests me, I have tried CLDiffServer.main but it seems not working. 
> Yes, the project structure is not good. It was written in a hurry and a lot of work needs to be done. Sorry for that.
> 
> > Though the test code can be helpful, complete documentations and comments in English are in urgent demand. Besides, the project structure can be improved. @calvinhkf
> > A small example:
> > https://github.com/FudanSELab/CLDIFF/blob/master/src/edu/fdu/se/cldiff/CLDiffTest.java

**Comment by kaifeng-h** [comment]
Hi there! I have uploaded web gui here
<https://github.com/FudanSELab/CLDIFF-WEB>. The web gui is ready, but STILL
some work on CLDIFF to make it running offline. You can check on that.

>

**Comment by monperrus** [comment]
Thanks.

> some work on CLDIFF to make it running offline
Looking forward to it.
