### ISSUE TITLE
There is a potential runtime exception

### ISSUE THREAD

**Issue by Liloveyang** [FudanSELab/CLDIFF#10]
Hello,

First of all i want to thank you for sharing your code.
But when I was operating some of my files, there was a runtime exception.

method1：edu.fdu.se.javaparser.JavaParserFactory.getCompilationUnit(InputStream is)

method2:  edu.fdu.se.javaparser.JavaParserFactory.getCompilationUnit(String filePath)

method3:  edu.fdu.se.base.generatingactions.JavaParserTreeGenerator.generate

When these three methods parse some files that are not syntax complete, The first two methods throw an exception of type com.github.javaparser.ParseProblemException, and The third method throws an exception of type  java.lang.SecurityException.but the caller may not know these problems and may cause the program to crash suddenly.

so I suggest you add catch or throw to the source code An exception goes out, which is convenient for the caller to develop. Thank you!

such as a not syntax complete java file content:

```
public class Test {
    private  BigDecimal d;
    public Test(BigDecimal val) {
        d =  val;
    }
    public static void main(String[] args) throws FileNotFoundException {
        FileInputStream fileInputStream = new FileInputStream(new File(""));
        getCompilationUnit(fileInputStream);
```

**Comment by kaifeng-h** [comment]
Yes. While running the code, we have presumed that the input files are syntax complete, which otherwise will raise an exception.

**Comment by kaifeng-h** [comment]
fix 2 of 3. Method  3 works fine.  see at 4bf95c617e9e1a5a147dbbdad0578c101dedf56c
