### ISSUE TITLE
Path separator on different OS

### ISSUE THREAD

**Issue by Symbolk** [FudanSELab/CLDIFF#3]
Since all the path separator is "/" in this project, so I guess it was developed on Linux/macOS.

Suggesting to use System.getProperty("file.separator") or File.separator as the path separator character, to make it exectuable on Windows.

See https://stackoverflow.com/questions/11241762/how-to-deal-with-different-file-separator-on-windows-and-unix-in-java?rq=1 for details.

**Comment by kaifeng-h** [comment]
There's many string."split"s, so I tried to unify it with "/". The project has been developed on Windows, but it works well with "/". If your have any issues, you can expain it further in detail.

**Comment by Symbolk** [comment]
OS: Windows 7 x64
JDK: 1.8.0_181
IDE: Intellij IDEA
Program arguments: D:\temp\cldiff\output D:\temp\cldiff\diff-match-patch
(Or the repoPath should be diff-match-patch\\.git ?)
When I run CLDIFFServerOffline.main(), there is an exception,  because the data.length=1: 

```java
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
	at main.CLDIFFServerOffline.main(CLDIFFServerOffline.java:38)
```

**Comment by kaifeng-h** [comment]
Yes, it should be the full path of the git directory, which is " D:\temp\cldiff\diff-match-patch\.git". 

> Program arguments: D:\temp\cldiff\output D:\temp\cldiff\diff-match-patch
> Or the repoPath should be diff-match-patch/.git ?)

**Comment by Symbolk** [comment]
Ok, but the Exception is caused by failure in ```Global.repoPath.split("/");```. Replacing the "/" with "\\\\" works fine.

**Comment by kaifeng-h** [comment]
Well, guess I can close the issue. Already fixed it, Now you can type input path either "\\" or "/".
