### ISSUE TITLE
feedback: what do you think of the TreeDiff file format?

### ISSUE THREAD

**Issue by monperrus** [FudanSELab/CLDIFF#5]
Hi,

We're working a common file format for the output of tree differencing tools. The idea is that many tree differencing tools would have an option to output this format. This would:
* ease building tools on top of tree differencing
* ease scientific experiments to compare the effectiveness of each tool on specific use cases.

Here is a first draft of the TreeDiff file format: https://docs.google.com/document/d/15ITrZ4c0qdb4rGLfaMt8K9VPG1CkNp5QSgfOY6jzpEk/edit?usp=sharing (comments can be left in the Gdoc)

What do you think? 

Best regards,

Jean-Rémy (@jrfaller), Matias (@martinezmatias) and Martin (@Monperrus) (authors of [Gumtree](https://github.com/GumTreeDiff/gumtree))

**Comment by kaifeng-h** [comment]
Hi, I think it's great if you unify diff tool formats. It would make it possible to implement the same front end, thus having less bias in  comparing diff tools when conducting user study.  
From my experience, I think files before and after, ast tree before and after and mappings are three key elements. But still I have a question: how to represent AST in json format? Are we still gonna parse the source code if we need the AST in further implementation?

In terms of diff format, I think _location-before-line-start_, _location-before-line-end_,  _location-after-line-start_, _location-after-line-end_ is also necessary?

**Comment by monperrus** [comment]
> how to represent AST in json format?

That's optional  in TreeDiff, and implementers of the file format can choose the one they want. 

* there is no unique AST for a given programming language
* there is no unique JSON format for a given AST.
* in [Gumtree-Spoon](https://github.com/SpoonLabs/gumtree-spoon-ast-diff/), the AST representation is the following: https://github.com/SpoonLabs/gumtree-spoon-ast-diff/blob/master/src/test/resources/examples/spoon.json

**Comment by kaifeng-h** [comment]
Please keep us informed if the file format is finished. And then I can make CLDiff comply to it. ^_^

**Comment by monperrus** [comment]
> Please keep us informed if the file format is finished. And then I can make CLDiff comply to it. ^_^
>
very good! the TreeDiff format will be finished soon, we'll ping you.
